name: Deploy to Google Cloud Functions

on:
  push:

jobs:
  deploy:
    strategy:
      matrix:
        node-version: [21.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Setup GCP credentials
        env:
          GCP_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}
        run: |
          gcloud auth activate-service-account --key-file /home/runner/GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY.json
          export GOOGLE_APPLICATION_CREDENTIALS=/home/runner/GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY.json

      - name: Deploy Cloud Function
        run: yarn deploy

      - name: Deploy Cloud getAllMatch Functions
        run: yarn deploy-getAllMatches
